= Error Handling Spring Boot Starter
:toc: macro
:toclevels: 3

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://travis-ci.org/wimdeblauwe/error-handling-spring-boot-starter.svg?branch=master["Build Status",link="https://travis-ci.org/wimdeblauwe/error-handling-spring-boot-starter"]

image:https://maven-badges.herokuapp.com/maven-central/io.github.wimdeblauwe/error-handling-spring-boot-starter/badge.svg["Maven Central",link="https://search.maven.org/search?q=a:error-handling-spring-boot-starter"]

toc::[]

== Goal

The goal of the project is to make it easy to have proper error responses for REST APIs build with Spring Boot.

== Usage

Add the dependency to your project.
For Maven:

[source,xml]
----
<dependency>
    <groupId>io.github.wimdeblauwe</groupId>
    <artifactId>error-handling-spring-boot-starter</artifactId>
    <version>LATEST_VERSION_HERE</version>
</dependency>
----

== What does this bring out-of-the-box?

=== Request body validation errors

Suppose there is a validation error for a request body that looks like this:

[source,java]
----
    public static class ExampleRequestBody {
        @Size(min = 10)
        private String name;
        @NotBlank
        private String favoriteMovie;

        // getters and setters
    }
----

When sending a JSON body like this:
[source,json]
----
{
    "name": "",
    "favoriteMovie": null
}
----

This is the default that Spring Boot gives:

[source,json]
----
{
  "timestamp": "2020-07-02T06:03:16.855+0000",
  "status": 400,
  "error": "Bad Request",
  "errors": [
    {
      "codes": [
        "Size.exampleRequestBody.name",
        "Size.name",
        "Size.java.lang.String",
        "Size"
      ],
      "arguments": [
        {
          "codes": [
            "exampleRequestBody.name",
            "name"
          ],
          "arguments": null,
          "defaultMessage": "name",
          "code": "name"
        },
        2147483647,
        10
      ],
      "defaultMessage": "size must be between 10 and 2147483647",
      "objectName": "exampleRequestBody",
      "field": "name",
      "rejectedValue": "",
      "bindingFailure": false,
      "code": "Size"
    },
    {
      "codes": [
        "NotBlank.exampleRequestBody.favoriteMovie",
        "NotBlank.favoriteMovie",
        "NotBlank.java.lang.String",
        "NotBlank"
      ],
      "arguments": [
        {
          "codes": [
            "exampleRequestBody.favoriteMovie",
            "favoriteMovie"
          ],
          "arguments": null,
          "defaultMessage": "favoriteMovie",
          "code": "favoriteMovie"
        }
      ],
      "defaultMessage": "must not be blank",
      "objectName": "exampleRequestBody",
      "field": "favoriteMovie",
      "rejectedValue": null,
      "bindingFailure": false,
      "code": "NotBlank"
    }
  ],
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "path": "/api/exception/invalidbody"
}
----

Using `error-handling-spring-boot-starter`, this becomes:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "fieldErrors": [
    {
      "code": "INVALID_SIZE",
      "property": "name",
      "message": "size must be between 10 and 2147483647",
      "rejectedValue": ""
    },
    {
      "code": "REQUIRED_NOT_BLANK",
      "property": "favoriteMovie",
      "message": "must not be blank",
      "rejectedValue": null
    }
  ]
}
----

==== Override the error code per validation annotation

It is possible to override the default codes that are used for each field error.

You need to use the following:

[source,properties]
----
error.handling.codes.Size=SIZE_REQUIREMENT_NOT_MET
----

So you start with `error.handling.codes` and suffix with the name of the validation annotation used (`@Size` in this example)

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "fieldErrors": [
    {
      "code": "SIZE_REQUIREMENT_NOT_MET", //<.>
      "property": "name",
      "message": "size must be between 10 and 2147483647",
      "rejectedValue": ""
    },
    {
      "code": "REQUIRED_NOT_BLANK",
      "property": "favoriteMovie",
      "message": "must not be blank",
      "rejectedValue": null
    }
  ]
}
----
<.> Custom code used for the field error

==== Override the error code for a specific field

It is possible to configure a specific error code that only will be used for a combination of a field with a validation annotation.

Suppose you add a regex to validate password rules:

[source,java]
----
public class CreateUserRequestBody {
    @Pattern(".*{8}")
    private String password;

    // getters and setters
}
----

By default, this error is in the response:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='createUserRequestBody'. Error count: 1",
  "fieldErrors": [
    {
      "code": "REGEX_PATTERN_VALIDATION_FAILED",
      "property": "password",
      "message": "must match \".*{8}\"",
      "rejectedValue": ""
    }
  ]
}
----

If we would use `error.handling.codes.Pattern` for the override, then all `@Pattern` annotations in the whole application would use a different code.
If we want to only override this for fields that are named `password`, we can use:

[source,properties]
----
error.handling.codes.password.Pattern=PASSWORD_COMPLEXITY_REQUIREMENTS_NOT_MET
----

This results in:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='createUserRequestBody'. Error count: 1",
  "fieldErrors": [
    {
      "code": "PASSWORD_COMPLEXITY_REQUIREMENTS_NOT_MET",
      "property": "password",
      "message": "must match \".*{8}\"",
      "rejectedValue": ""
    }
  ]
}
----

==== Override the error message per validation annotation

It is possible to override the default messages that are used for each field error.

You need to use the following:

[source,properties]
----
error.handling.messages.NotBlank=The property should not be blank
----

So you start with `error.handling.messages` and suffix with the name of the validation annotation used (`@NotBlank` in this example)

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 1",
  "fieldErrors": [
    {
      "code": "REQUIRED_NOT_BLANK",
      "property": "name",
      "message": "The property should not be blank",//<.>
      "rejectedValue": ""
    }
  ]
}
----
<.> Custom message used for the field error

==== Override the error message for a specific field

It is possible to configure a specific error message that only will be used for a combination of a field with a validation annotation.

Suppose you add a regex to validate password rules:

[source,java]
----
public class CreateUserRequestBody {
    @Pattern(".*{8}")
    private String password;

    // getters and setters
}
----

By default, this error is in the response:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='createUserRequestBody'. Error count: 1",
  "fieldErrors": [
    {
      "code": "REGEX_PATTERN_VALIDATION_FAILED",
      "property": "password",
      "message": "must match \".*{8}\"",
      "rejectedValue": ""
    }
  ]
}
----

If we would use `error.handling.messages.Pattern` for the override, then all `@Pattern` annotations in the whole application would use a different message.
If we want to only override this for fields that are named `password`, we can use:

[source,properties]
----
error.handling.messages.password.Pattern=The password complexity rules are not met. A password must be 8 characters minimum.
----

This results in:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='createUserRequestBody'. Error count: 1",
  "fieldErrors": [
    {
      "code": "REGEX_PATTERN_VALIDATION_FAILED",
      "property": "password",
      "message": "The password complexity rules are not met. A password must be 8 characters minimum.",
      "rejectedValue": ""
    }
  ]
}
----

==== Global errors

If there would be global errors next to the field related errors, they would appear under the `globalErrors` property:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "globalErrors": [
    {
      "code": "ValidCustomer",
      "message": "Invalid customer"
    },
    {
      "code": "ValidCustomer",
      "message": "UserAlreadyExists"
    }
  ]
}
----

The `code` and `message` used is based on the annotation that was used for validation:

[source,java]
----
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Constraint(validatedBy = CustomerValidator.class)
public @interface ValidCustomer {
    String message() default "Invalid customer";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}
----

As well as the template that is used in the validator itself:

[source,java]
----
public class CustomerValidator implements ConstraintValidator<ValidCustomer, CreateCustomerFormData> {
    @Override
    public boolean isValid(CreateCustomerFormData formData, ConstraintValidatorContext context) {

        if(...) {
            context.buildConstraintViolationWithTemplate("UserAlreadyExists").addConstraintViolation();
        }
    }
}
----

==== Override codes in field errors and global errors

Using the `error.handling.codes` property in `application.properties`, the used codes can be overridden.
Suppose you have this:

[source,properties]
----
error.handling.codes.NotBlank=NOT_BLANK
error.handling.codes.Size=BAD_SIZE
error.handling.codes.ValidCustomer=INVALID_CUSTOMER
----

Then the resulting response for the field errors example will be:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "fieldErrors": [
    {
      "code": "BAD_SIZE",
      "property": "name",
      "message": "size must be between 10 and 2147483647",
      "rejectedValue": ""
    },
    {
      "code": "NOT_BLANK",
      "property": "favoriteMovie",
      "message": "must not be blank",
      "rejectedValue": null
    }
  ]
}
----

And for the global errors example:

[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "globalErrors": [
    {
      "code": "INVALID_CUSTOMER",
      "message": "Invalid customer"
    },
    {
      "code": "INVALID_CUSTOMER",
      "message": "UserAlreadyExists"
    }
  ]
}
----

[NOTE]
====
If you want to change the message for the global errors, the default Spring mechanismn to do see keeps working.

So use `{}` to indicate that Spring should search the `messages.properties` file:
[source,java]
----
context.buildConstraintViolationWithTemplate("{UserAlreadyExists}").addConstraintViolation();
----

Now add the translation to the `messages.properties`:
[source,properties]
----
UserAlreadyExists=The user already exists
----

This results in:
[source,json]
----
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "globalErrors": [
    {
      "code": "INVALID_CUSTOMER",
      "message": "Invalid customer"
    },
    {
      "code": "INVALID_CUSTOMER",
      "message": "The user already exists"
    }
  ]
}
----

====

=== Type conversion exceptions

Type conversion exceptions like `MethodArgumentTypeMismatchException` and `TypeMismatchException` will have some extra info about the class that was expected and the value that was rejected:

[source,json]
----
{
  "code": "ARGUMENT_TYPE_MISMATCH",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'com.example.user.UserId'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.web.bind.annotation.PathVariable com.example.user.UserId] for value 'fake_UUID'; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: fake_UUID",
  "expectedType": "com.example.user.UserId",
  "property": "userId",
  "rejectedValue": "fake_UUID"
}
----

=== Optimistic locking exceptions

When an `org.springframework.orm.ObjectOptimisticLockingFailureException` is thrown, the resulting response will be something like:

[source,json]
----
{
  "code": "OPTIMISTIC_LOCKING_ERROR",
  "message": "Object of class [com.example.user.User] with identifier [87518c6b-1ba7-4757-a5d9-46e84c539f43]: optimistic locking failed",
  "identifier": "87518c6b-1ba7-4757-a5d9-46e84c539f43",
  "persistentClassName": "com.example.user.User"
}
----

=== Spring Security exceptions

If Spring Security is on the classpath, then those exceptions will be handled.
They will just have a `code` and a `message`.

For example:

[source,json]
----
{
  "code": "ACCESS_DENIED",
  "message": "Access is denied"
}
----

=== Custom exceptions

If you define a custom Exception and throw that from a `@RestController` method, then Spring Boot will turn this into a `500 INTERNAL SERVER ERROR` by default.
The response status is easily changed by using `@ResponseStatus`:

[source,java]
----
@ResponseStatus(HttpStatus.NOT_FOUND)
public class UserNotFoundException extends RuntimeException {
    public UserNotFoundException(UserId userId) {
        super(String.format("Could not find user with id %s", userId));
    }
}
----

This is the Spring Boot default response for this:

[source,json]
----
{
  "timestamp": "2020-07-02T06:06:41.400+0000",
  "status": 404,
  "error": "Not Found",
  "message": "Could not find user with id UserId{id=b8285c14-06bd-41db-a4df-724d0d1e590b}",
  "path": "/api/exception/test"
}
----

Using `error-handling-spring-boot-starter`, this becomes:

[source,json]
----
{
  "code": "com.application.backend.user.UserNotFoundException",
  "message": "Could not find user with id UserId{id=a6cd68f2-b305-4b2d-8442-ee1696e6eb8f}"
}
----

We can now further enhance the response in several ways:

* Override the HTTP response status
* Set the code to use instead of the full qualified name of the Exception class
* Change the default strategy to convert the name of the Exception to a `code`
* Add additional fields to enrich the error response

==== Override the HTTP response status

By default, all custom exceptions will use the _500 INTERNAL SERVER ERROR_ response code.

To override this, you can use `@ResponseStatus(HttpStatus.NOT_FOUND)` for Exception types that you control.

For Exception types outside of your control, you can configure this through the `error.handling.http-statuses` property:

[source,properties]
----
error.handling.http-statuses.java.lang.IllegalArgumentException=BAD_REQUEST
----

Anytime an `IllegalArgumentException` is thrown the _400 BAD REQUEST_ response code is used instead of the default _500 INTERNAL SERVER ERROR_.

The possible values are any of the https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html[org.springframework.http.HttpStatus] enum values.

==== Setting the error code

To override the error code, we change the exception class to:

[source,java]
----
@ResponseStatus(HttpStatus.NOT_FOUND)
@ResponseErrorCode("USER_NOT_FOUND") // <.>
public class UserNotFoundException extends RuntimeException {
    public UserNotFoundException(UserId userId) {
        super(String.format("Could not find user with id %s", userId));
    }
}
----
<.> Set the error code that should be used in the response when this Exception is thrown from a `@RestController` method.

The resulting response:

[source,json]
----
{
  "code": "USER_NOT_FOUND",
  "message": "Could not find user with id UserId{id=8c7fb13c-0924-47d4-821a-36f73558c898}"
}
----

==== Change the default strategy to determine the error code

Set the `error.handling.default-error-code-strategy` property to change how the library generates the code automatically.
By default, the `FULL_QUALIFIED_NAME` strategy is used, which gives:

[source,json]
----
{
  "code": "com.application.backend.user.UserNotFoundException",
  "message": "Could not find user with id UserId{id=a6cd68f2-b305-4b2d-8442-ee1696e6eb8f}"
}
----

By changing this to use `ALL_CAPS_CONVERSION` like this:

[source,properties]
----
error.handling.default-error-code-strategy=ALL_CAPS_CONVERSION
----

We get:

[source,json]
----
{
  "code": "USER_NOT_FOUND",
  "message": "Could not find user with id UserId{id=a6cd68f2-b305-4b2d-8442-ee1696e6eb8f}"
}
----

NOTE: The `Exception` part at the end of the class name is removed to build the code.

==== Setting the error code via properties

It is also possible to set the error code via `application.properties`.

Suppose some method throws an `com.amazonaws.AmazonClientException`.
We can't annotate the class with `@ResponseErrorCode` since it is 3rd party code.

To set an error code, add the following to your `application.properties`:

[source,properties]
----
error.handling.codes.com.amazonaws.AmazonClientException=CLOUD_PROVIDER_ERROR
----

The resulting response:
[source,json]
----
{
  "code": "CLOUD_PROVIDER_ERROR",
  "message": "Some exception message from Amazon here"
}
----


==== Adding extra properties in the response

To add extra properties in the error response, you can annotate fields and/or methods on your exception classes with `@ResponseErrorProperty`. For example:

[source,java]
----
@ResponseStatus(HttpStatus.NOT_FOUND)
@ResponseErrorCode("USER_NOT_FOUND")
public class UserNotFoundException extends RuntimeException {

    private final UserId userId;

    public UserNotFoundException(UserId userId) {
        super(String.format("Could not find user with id %s", userId));
        this.userId = userId;
    }

    @ResponseErrorProperty // <.>
    public String getUserId() {
        return userId.asString();
    }
}
----
<.> Add the result of this method as an extra property in the response

The resulting response:
[source,json]
----
{
  "code": "USER_NOT_FOUND",
  "message": "Could not find user with id UserId{id=8c7fb13c-0924-47d4-821a-36f73558c898}",
  "userId": "8c7fb13c-0924-47d4-821a-36f73558c898"
}
----

The `@ResponseErrorProperty` can be used on a method or on a field.

==== Overriding the property name

It is also possible to override the property name that will be used in the response by using the `value` argument of the annotation.

[source,java]
----
@ResponseStatus(HttpStatus.NOT_FOUND)
@ResponseErrorCode("USER_NOT_FOUND")
public class UserNotFoundException extends RuntimeException {

    ...

    @ResponseErrorProperty("id")
    public String getUserId() {
        return userId.asString();
    }
}
----


The resulting response:

[source,json]
----
{
  "code": "USER_NOT_FOUND",
  "message": "Could not find user with id UserId{id=8c7fb13c-0924-47d4-821a-36f73558c898}",
  "id": "8c7fb13c-0924-47d4-821a-36f73558c898"
}
----

==== Null handling

If a property or method that is annotated with `@ResponseErrorProperty` returns `null`, then the JSON output will not contain the property by default.
If this is desirable, then use the `includeIfNull` property on the annotation to change this behaviour:

[source,java]
----
@ResponseStatus(HttpStatus.NOT_FOUND)
@ResponseErrorCode("USER_NOT_FOUND")
public class UserNotFoundException extends RuntimeException {

    private final UserId userId;

    public UserNotFoundException(UserId userId) {
        super(String.format("Could not find user with id %s", userId));
        this.userId = userId;
    }

    @ResponseErrorProperty(includeIfNull=true) // <.>
    public String getUserId() {
        return userId.asString();
    }
}
----
<.> Set the `includeIfNull` setting to `true`

The resulting response assuming the passed in `userId` is `null`:

[source,json]
----
{
  "code": "USER_NOT_FOUND",
  "message": "Could not find user with id UserId{id=8c7fb13c-0924-47d4-821a-36f73558c898}",
  "userId": null
}
----

== Properties

|===
|Property |Description|Default

|error.handling.enabled
|Allows to enable or disable the error handling
|true

|error.handling.exception-logging
|Allows to set how the exception should be logged.
One of: `NO_LOGGING`, `MESSAGE_ONLY`,
`WITH_STACKTRACE`.
|MESSAGE_ONLY

|error.handling.default-error-code-strategy
|Determines how an Exception is converted into a `code` in case there is no `@ResponseErrorCode` present on the class.
One of `FULL_QUALIFIED_NAME`, `ALL_CAPS_CONVERSION`.
|`FULL_QUALIFIED_NAME`

|error.handling.http-statuses
|Allows to set the HttpStatus response code to use for the full qualified name of an `Exception`
| `HttpStatus.INTERNAL_SERVER_ERROR` is used for custom exceptions have no specific response status set here.

|error.handling.codes
|Allows to set the code that should be used for the full qualified name of an `Exception`
|

|error.handling.json-field-names.code
|The field name that is used to serialize the `code` to JSON.
|`code`

|error.handling.json-field-names.message
|The field name that is used to serialize the `message` to JSON.
|`message`

|error.handling.json-field-names.fieldErrors
|The field name that is used to serialize the `fieldErrors` to JSON.
|`fieldErrors`

|error.handling.json-field-names.globalErrors
|The field name that is used to serialize the `globalErrors` to JSON.
|`globalErrors`

|===

== Release

Release is done via the Maven Release Plugin:

`mvn release:prepare`

and

`mvn release:perform`

Finally, push the local commits and the tag to remote.

[NOTE]
====
Before releasing, run `export GPG_TTY=$(tty)`
====
