= Error Handling Spring Boot Starter
:toc: macro
:toclevels: 3

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://github.com/wimdeblauwe/error-handling-spring-boot-starter/actions/workflows/build.yml/badge.svg[]

image:https://maven-badges.herokuapp.com/maven-central/io.github.wimdeblauwe/error-handling-spring-boot-starter/badge.svg["Maven Central",link="https://search.maven.org/search?q=a:error-handling-spring-boot-starter"]

toc::[]

== Goal

The goal of the project is to make it easy to have proper and consistent error responses for REST APIs build with Spring Boot.

== Documentation

See https://wimdeblauwe.github.io/error-handling-spring-boot-starter for the extensive documentation.

If you are new to the library, check out https://foojay.io/today/better-error-handling-for-your-spring-boot-rest-apis/[Better Error Handling for Your Spring Boot REST APIs] for an introductory overview.

NOTE: Documentation is very important to us, so if you find something missing from the docs, please create an issue about it.

== Spring Boot compatibility

|===
|error-handling-spring-boot-starter |Spring Boot|Minimum Java version

|https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/3.3.0[3.3.0]
|2.7.x
|11

|https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/3.2.0[3.2.0]
|2.5.x
|11

|https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/2.1.0[2.1.0]
|2.5.x
|11

|https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/1.7.0[1.7.0]
|2.2.x
|8

|===

== Articles

Blogs and articles about this library:

* https://foojay.io/today/better-error-handling-for-your-spring-boot-rest-apis/[Better Error Handling for Your Spring Boot REST APIs] - Nice article on foojay.io that explains the library in detail
* https://www.wimdeblauwe.com/blog/2021/05/01/error-handling-spring-boot-starter-release-1.6.0/[Error Handling Spring Boot Starter release 1.6.0] - Blog post explaining the updates in version 1.6.0
* https://www.wimdeblauwe.com/blog/2020/07/20/error-handling-library-spring-boot/[Error handling library for Spring Boot] - Original blog post that introduced the library

== Release

Release is done via the Maven Release Plugin:

`mvn release:prepare`

and

`mvn release:perform`

Merge the tag to `master` so the documentation is updated.

Finally, push the local commits and the tag to remote.

[NOTE]
====
Before releasing, run `export GPG_TTY=$(tty)`
====
